/**
 * Created by wangtun on 2016/7/21.
 */
const actionEnum = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  GET_VISITOR_DATA: 'GET_VISITOR_DATA',
  GET_SINGLE_DATA: 'GET_SINGLE_DATA',
  SET_CHARGE_LIST: 'SET_CHARGE_LIST',
  SET_LOCATION_TO_MAP: 'SET_LOCATION_TO_MAP',
  SET_CHARGE_MAP_LIST: 'SET_CHARGE_MAP_LIST',
  SET_CUSTOM_OWN_DATA: 'SET_CUSTOM_OWN_DATA',
  LOCATION_FLAG_BACK: 'LOCATION_FLAG_BACK',
};

export default actionEnum;
